# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
javax-servlet-servlet-api = "2.5"
org-apache-httpcomponents-httpclient = "4.5.14"
org-apache-httpcomponents-httpcore = "4.4.16"
org-json-json = "20220924"

[libraries]
javax-servlet-servlet-api = { module = "javax.servlet:servlet-api", version.ref = "javax-servlet-servlet-api" }
org-apache-httpcomponents-httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "org-apache-httpcomponents-httpclient" }
org-apache-httpcomponents-httpcore = { module = "org.apache.httpcomponents:httpcore", version.ref = "org-apache-httpcomponents-httpcore" }
org-json-json = { module = "org.json:json", version.ref = "org-json-json" }

[plugins]
dependencyCheck = { id = "org.owasp.dependencycheck", version = "9.2.0" }
