# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
javax-servlet-servlet-api = "2.5"
org-apache-httpcomponents-httpclient = "4.5.14"
org-apache-httpcomponents-httpcore = "4.4.16"
org-json-json = "20220924"

[libraries]
com-sun-xml-messaging-saaj-saajImpl = { module = "com.sun.xml.messaging.saaj:saaj-impl", version = "1.3.28" }
javax-servlet-servletApi = { module = "javax.servlet:servlet-api", version.ref = "javax-servlet-servlet-api" }
org-apache-httpcomponents-httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "org-apache-httpcomponents-httpclient" }
org-apache-httpcomponents-httpcore = { module = "org.apache.httpcomponents:httpcore", version.ref = "org-apache-httpcomponents-httpcore" }
org-json-json = { module = "org.json:json", version.ref = "org-json-json" }
org-slf4j-slf4jApi = { module = "org.slf4j:slf4j-api", version = "1.7.30" }
org-slf4j-slf4jLog4j12 = {module = "org.slf4j:slf4j-log4j12", version = "1.7.30" }
org-apache-logging-log4j-log4jCore = { module = "org.apache.logging.log4j:log4j-core", version = "2.17.1" }
junit-junit = { module = "junit:junit", version = "4.13.1" }

licenseGradlePlugin = { module = "gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin", version = "0.16.1" }

[bundles]
testImplementation = [ "junit-junit", "org-slf4j-slf4jApi", "org-slf4j-slf4jLog4j12", "org-apache-logging-log4j-log4jCore" ]


[plugins]
dependencyCheck = { id = "org.owasp.dependencycheck", version = "9.2.0" }
